### ISSUE TITLE
Memory Leaks found after close server

### ISSUE THREAD

**Issue by jeanroyce** [idathena/trunk#14]
Hi, I am getting memory leak errors after turning off the server in last version 4828daa
![sem titulo](https://cloud.githubusercontent.com/assets/8617825/12330497/3821cd04-bac4-11e5-8872-5188a87cbba7.png)

**Comment by exneval** [comment]
I find hard for fixing this issue, from what I see in pict :
map.c line 3967
`RECREATE(map[m].qi_data, struct questinfo, ++map[m].qi_count);`
script.c line 17760
`RECREATE(qi->jobid, unsigned short, qi->jobid_count + 1);`
script.c line 17877
`RECREATE(qi->req, struct questinfo_req, qi->req_count + 1);`

all of those lines are RECREATE,
I'm guessing when trying to recreate, there's a memory from variables not been freed first?

@cydh can you help us? since you're the author for this code (*questinfo)
I can't create an issue in rA cause, the line information from the pict. might not be the same

**Comment by cydh** [comment]
Let's see if I can do something

**Comment by exneval** [comment]
thanks as always @cydh

**Comment by exneval** [comment]
Hope fixed in f499ac1
