### ISSUE TITLE
new updates from rathena and other emulator

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#19]
sir @exneval ! good day! there  are many updates in other emulator must merge it here in idathena! i look forward to it sir. please because i want using your emulator :)

**Comment by exneval** [comment]
Hello there, first of all, thank you for asking me about idA future. I also understand that others are already doing some great updates, especially rA and idA need to merge them.

I will say that idA will merge them, but it may take times to do that because right now I've been struggling with my study (final test), and when it is done, I promise will continue the project. I am really sorry for this issue, hope you guys can understand.

**Comment by ernestfegarido** [comment]
thank you sir @exneval ! goodluck on your final exam! ill just wait for the updates!
