### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ernestfegarido** [idathena/trunk#96]
are you still continuing to update this project? :( pls continue it i love this emulator! @nanakiwurtz @exneval @cydh @jetkappu  :+1:

**Comment by cydh** [comment]
From me, u dont need to mention me in every issue u made. I'm not part of
this project since years
On Jul 1, 2016 13:38, "ernestfegarido" <notifications@github.com> wrote:

are you still continuing to update this project? :( pls continue it i love
this emulator! @nanakiwurtz <https://github.com/nanakiwurtz> @exneval
<https://github.com/exneval> @cydh <https://github.com/cydh> @jetkappu
<https://github.com/jetkappu> 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/idathena/trunk/issues/96>, or mute the thread
<https://github.com/notifications/unsubscribe/AD1K4K8etR13FfgfOOGam_0SPioOFy3bks5qRLXcgaJpZM4JC29L>
.

**Comment by exneval** [comment]
Halo thanks for bringing up this issue, currently I'm not in stable condition to update changes from rA, if you really want the specific rA update really bad, you can give me the commit hash by posting it here. And if you have to create another issue, it's not necessary to mention all of the devs, just by post it, we already know and will read or reply it. Thanks

**Comment by ernestfegarido** [comment]
alright sorry for mentioning all of you i just want this project to be updated and better :) by the way im not familiar with the hash thing how to reproduce it? :)

**Comment by exneval** [comment]
When you seeing rA update, you will find the alphabets in the link as the revision hash, such as git hash "abcdefg"

**Comment by ernestfegarido** [comment]
for example this one? "11179e3d43bee6528ec8966a792bfb9d3dc71e8a"

**Comment by exneval** [comment]
Just the first seven alphabets is fine, thanks

**Comment by ernestfegarido** [comment]
i will just wait for your further updates :(
